language: node_js
node_js:
- node
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: VAtWRgaZz0qluN6IFhOcHMoxF3okmFrXUlR1IxSNCQLQ+kKDUwjpDs+N1PpB6IkpOVzzleIy5Eh4LVW8cYPzkHjyUcLtcB45X1oVBjyexFnn6GZ/t1qSjbYQEInZiJ76WxzhNHp7U5baDbVG/qd/R9LETL2MJcBvq5h2VO8KVkjlh/5A6o9qXJeD37H2lcaUbEkEiBGUzCZeEFzc/xNhYfHJKa5NyMVt8hU7AjbsBvLZ2cc+re0kAYWzE8m53gyFrarxGKOsSJUBI1cCqlIhBPpd22lyUNWdPju7dnqpCogkE3dZ9XabLZGa5IuFX56OlbTCy81VpwaooEWJ53+dALKEriRrmzZr78W6RRbCJvZ6SB6XSEqjMglPV1Qiq+eBvuV4irXaBB5duHqgQt+kzAjuYBEgYPeAKBsn4wRoeSFAVbv8t/Ft82TLgM2G/yBEyR0/2+TBLBdKqg9tBo1kZRerhjBYtqflxRc1FIyo+uuy8rgr5LpbwpNT2nQPXIJD8FSVhsnTH1SUMoRtjBkjz4vORdnfL7S13K0FCK+r7PheXCcV8AlLwRotszbG5WBGCMaj3sipxcivStZS8Aui6PVcoDZkTCBQudE9ewC+3OOb5ZiBrYtaDjLU3uHjYiUfNF22RBTGNjS8Cpex5QDY1PPgHpJ3Y/ws37B7L4LCK2U=
  app: random-cocktail-generator
  skip-cleanup: true