language: node_js
node_js:
- node
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: fgxrt2SS+N58vLCNUp+bkOzuWo5vNXHRpFlmn07bNO5+0/Gb6bBi6drrMu8VYqPoahhvE8soTf8wKW6q3kEpzbRyQaFXPn+2nFcMpxzj6r0K9yCTNBYZEQ/s6bBaH5v61UvXOI9bx7cDG31jyroJIe+Nxy3bHzbNZN82SVMlaH+LHs8GKZD0z7qCJ/x35/V1dClekOMxxjXYW75/YFQHhKUJJ3rJ2h9zn5CnT/RTkFEspri7VomsuX5XbJtf8fGh1GpMTXUUtzpGvpY9L+XV4mIHOWw37c2Zd35/YzRJ6n+JfeoUZBgE+TA3gjO0znBkoocMwFFKKRB2QkFbOIHkZVxMVEWPt2/QbK2Rbcl/R5O9I/d/oBS9Jlp72gEAQrONsAqsisuqZoJI7wD9AQ1s3ixt9RxgJ80Bc8HUmSyD8Z6z0BBNFNoQL2O0NNr8VYz/rwNcUGLcEV/kSPWXMMsRA5w7RREhzbYoi/yc3lQa4Dx7xjUH+FsTNYBOHiyZPszZAEjucTHkhLd554LYdNEOlJ6Jb7t0YXgaPAMlB3xM3l0ysKUxpCMiq/1suFBCT6qzZ0Xna/jhKYYKdIeMOj6o52Y/mPDm3YahQwpmdVcOjylgOTsS4WVOBzQX9BYGoYxttB8nBe/DmuGMDZRA+zt7j5W2TM9P4qQ+TduYoueUF7I=
  app: random-cocktail-generator
  skip-cleanup: true
